enforce_dependencies: true
enforce_privacy: true
dependencies:
  - packages/organizations
  - packages/lawyer_profiles
  - packages/tax_incomes
  - packages/payouts
  - packages/authentication
  - packages/transactions