name: Deployment

env:
  AR_LOCATION: eu
  REGION: europe-southwest1 # Madridoo
  RWX_ACCESS_TOKEN: ${{ secrets.RWX_ACCESS_TOKEN }}


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:14-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres

      redis:
        image: redis:alpine
        ports: ['6379:6379']

    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://localhost:6379/0
      RAILS_ENV: test
      DISABLE_SPRING: true
      CI: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true


      - name: Lint with RuboCop
        run: bin/rubocop --parallel

      - name: Setup PostgreSQL
        run: bin/rails db:create
  
      - uses: rwx-research/setup-captain@v1
      - name: Run RSpec \w Captain
        run: |
          captain run \
            --suite-id errentaeus-rspec \
            --test-results tmp/rspec.json \
            -- \
            bundle exec rspec \
              --format json --out tmp/rspec.json \
              --format progress

  build_image:

    needs: test

    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    environment: gcp

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build the image
        run: |
          export COMMIT_TIME=$(git show -s --format=%cI ${GITHUB_SHA})
          export COMMIT_VERSION=$(git describe --always)
          echo $GITHUB_SHA
          echo $COMMIT_TIME
          echo $COMMIT_VERSION
          docker buildx build --build-arg COMMIT_TIME --build-arg COMMIT_VERSION -t app .
      - name: Push the image tagged with version to the container registry
        run: |
          docker tag app ${{ env.AR_LOCATION }}.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
          docker push ${{ env.AR_LOCATION }}.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

  launch_deployment:
    needs: build_image
    environment: gcp
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' 

      - id: 'Deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'errentaeusruby'
          image: '${{ env.AR_LOCATION }}.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}'
          project_id: ${{ secrets.PROJECT_ID }}
          region: europe-west1
          env_vars: |
            APP_DOMAIN_COOKIES=.errenta.eus
            FRONTEND_APP_HOST=.errenta.eus

          secrets: |
            DB_PASSWORD=ERRENTA-DBPASSWORD:latest
            STRIPE_SECRET_TEST_KEY=STRIPE_SECRET_TEST_KEY:latest
            STRIPE_SIGNING_TEST_SECRET=STRIPE_SIGNING_TEST_SECRET:latest
            VAPID_PUBLIC=ERRENTA-VAPID-PUBLIC:1
            VAPID_PRIVATE=ERRENTA-VAPID-PRIVATE:1
          flags: |
            --set-cloudsql-instances=eliza-asesores:europe-west4:errenta

      - name: 'Notify deployment'
        uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}