name: testfly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app errenta
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
